<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Beasiswa;
use Carbon\Carbon;

class BeasiswaSeeder extends Seeder
{
    public function run()
    {
        $beasiswas = [
            // === BEASISWA DALAM NEGERI ===
            [
                'nama' => 'KIP Kuliah 2025',
                'deskripsi' => 'Bantuan biaya pendidikan dari pemerintah untuk calon mahasiswa baru dari keluarga kurang mampu yang memiliki prestasi akademik baik. Mencakup biaya kuliah penuh dan biaya hidup bulanan.',
                'universitas' => 'PTN & PTS Terakreditasi',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(6),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://kip-kuliah.kemdikbud.go.id',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Unggulan Kemendikbud Merdeka 2025',
                'deskripsi' => 'Beasiswa prestasi untuk calon mahasiswa baru yang memiliki prestasi akademik atau non-akademik tingkat nasional/internasional. Khusus untuk siswa SMA/SMK yang berprestasi.',
                'universitas' => 'Universitas Dalam Negeri Pilihan',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(8),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://beasiswaunggulan.kemdikbud.go.id',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Bidikmisi (Transisi KIP)',
                'deskripsi' => 'Program beasiswa bagi lulusan SMA/SMK dari keluarga tidak mampu secara ekonomi namun memiliki potensi akademik baik untuk melanjutkan pendidikan S1.',
                'universitas' => 'PTN Se-Indonesia',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(5),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://bidikmisi.belmawa.ristekdikti.go.id',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Tanoto Foundation Fresh Graduate 2025',
                'deskripsi' => 'Program beasiswa untuk siswa berprestasi dari keluarga kurang mampu yang diterima di universitas mitra Tanoto Foundation melalui jalur SNBP, SNBT, atau Mandiri.',
                'universitas' => 'Universitas Partner (IPB, ITB, UNAIR, dll)',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(7),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://tanotofoundation.org/id/beasiswa',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Orbit Future Academy Fresh Graduate 2025',
                'deskripsi' => 'Beasiswa penuh untuk lulusan SMA/SMK yang ingin kuliah di bidang teknologi informasi dan komputer. Mencakup uang kuliah, laptop, dan magang.',
                'universitas' => 'Berbagai Universitas IT',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Teknologi & IT',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(6),
                'jurusan' => 'Teknik Informatika, Sistem Informasi, Ilmu Komputer',
                'link_pendaftaran' => 'https://orbitfutureacademy.id',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Karya Salemba Empat (KSE) 2025',
                'deskripsi' => 'Beasiswa untuk mahasiswa baru dari keluarga pra sejahtera yang diterima di PTN melalui jalur prestasi dengan nilai akademik baik.',
                'universitas' => 'PTN Favorit (UI, ITB, UGM, ITS, IPB, UNPAD)',
                'jenis_beasiswa' => 'Beasiswa Parsial',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(4),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://www.beasiswakse.org',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Etos Fresh Graduate 2025',
                'deskripsi' => 'Beasiswa dari Dompet Dhuafa untuk lulusan SMA/SMK yang kurang mampu namun berprestasi untuk kuliah di PTN/PTS.',
                'universitas' => 'PTN & PTS Terpilih',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(5),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://beasiswa.dompetdhuafa.org',
                'gambar' => null,
            ],
            [
                'nama' => 'Beasiswa Baznas Fresh Graduate 2025',
                'deskripsi' => 'Program beasiswa dari Badan Amil Zakat Nasional untuk calon mahasiswa baru dari keluarga mustahik (penerima zakat) yang berprestasi.',
                'universitas' => 'PTN & PTS Terpilih',
                'jenis_beasiswa' => 'Beasiswa Parsial',
                'kategori' => 'Semua Bidang',
                'negara' => 'Indonesia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(6),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://baznas.go.id/beasiswa',
                'gambar' => null,
            ],

            // === BEASISWA LUAR NEGERI ===
            [
                'nama' => 'MEXT Scholarship Japan Undergraduate 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Jepang untuk lulusan SMA yang ingin kuliah S1 di Jepang. Mencakup tiket PP, uang kuliah, dan biaya hidup bulanan.',
                'universitas' => 'Universitas di Jepang',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Sains & Teknologi',
                'negara' => 'Jepang',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(9),
                'jurusan' => 'Teknik, Sains, Kedokteran, Pertanian',
                'link_pendaftaran' => 'https://www.studyinjapan.go.jp',
                'gambar' => null,
            ],
            [
                'nama' => 'KGSP Korean Government Scholarship Undergraduate 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Korea untuk lulusan SMA/SMK yang ingin kuliah S1 di Korea Selatan. Termasuk kursus bahasa Korea 1 tahun.',
                'universitas' => 'Universitas di Korea Selatan',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Korea Selatan',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(10),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://www.studyinkorea.go.kr',
                'gambar' => null,
            ],
            [
                'nama' => 'Australia Awards Scholarship Undergraduate 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Australia untuk siswa berprestasi dari Indonesia yang ingin kuliah S1 di Australia.',
                'universitas' => 'Universitas di Australia',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Australia',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(11),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://www.australiaawardsindonesia.org',
                'gambar' => null,
            ],
            [
                'nama' => 'Turkey Scholarship Undergraduate 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Turki untuk lulusan SMA yang ingin kuliah S1 di Turki. Mencakup akomodasi, tiket, dan biaya hidup.',
                'universitas' => 'Universitas di Turki',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Turki',
                'status' => 'Open',
                'deadline' => Carbon::now()->addYear(),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://www.turkiyeburslari.gov.tr',
                'gambar' => null,
            ],
            [
                'nama' => 'Chinese Government Scholarship Undergraduate 2025',
                'deskripsi' => 'Beasiswa dari pemerintah China untuk mahasiswa internasional yang ingin kuliah S1 di China dengan program bahasa Mandarin.',
                'universitas' => 'Universitas di China',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'China',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(8),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://www.campuschina.org',
                'gambar' => null,
            ],
            [
                'nama' => 'Hungary Stipendium Hungaricum Undergraduate 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Hungaria untuk siswa internasional yang ingin kuliah S1 di Hungaria dengan berbagai pilihan program.',
                'universitas' => 'Universitas di Hungaria',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Semua Bidang',
                'negara' => 'Hungaria',
                'status' => 'Open',
                'deadline' => Carbon::now()->addMonths(7),
                'jurusan' => 'Semua Jurusan',
                'link_pendaftaran' => 'https://stipendiumhungaricum.hu',
                'gambar' => null,
            ],
            [
                'nama' => 'Swiss Government Excellence Scholarship 2025',
                'deskripsi' => 'Beasiswa dari pemerintah Swiss untuk mahasiswa internasional berprestasi yang ingin kuliah di Swiss. Program sangat kompetitif.',
                'universitas' => 'Universitas di Swiss',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'kategori' => 'Sains & Teknologi',
                'negara' => 'Swiss',
                'status' => 'Open',
                'deadline' => Carbon::now()->addYear(),
                'jurusan' => 'Teknik, Sains, Kedokteran',
                'link_pendaftaran' => 'https://www.sbfi.admin.ch/scholarships_eng',
                'gambar' => null,
            ],
        ];

        foreach ($beasiswas as $beasiswa) {
            Beasiswa::create($beasiswa);
        }
    }
}
