<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Beasiswa;
use Carbon\Carbon;

class BeasiswaSeeder extends Seeder
{
    public function run()
    {
        $beasiswas = [
            // Beasiswa Dalam Negeri
            [
                'nama' => 'Beasiswa LPDP 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah untuk studi S2 dan S3 di dalam dan luar negeri',
                'universitas' => 'Berbagai Universitas',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S2',
                'kategori' => 'Ekonomi & Bisnis',
                'negara' => 'Indonesia',
                'status' => 'Open', // Ubah dari 'Aktif' menjadi 'Open' atau status yang lebih pendek
                'deadline' => Carbon::now()->addMonths(2),
                'ipk_minimal' => 3.00,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'KIP Kuliah 2025',
                'deskripsi' => 'Bantuan biaya pendidikan untuk mahasiswa kurang mampu berprestasi',
                'universitas' => 'Seluruh PTN/PTS',
                'jenis_beasiswa' => 'KIP Kuliah',
                'jenjang' => 'S1',
                'kategori' => 'Sains & Teknologi',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(3),
                'ipk_minimal' => null,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Beasiswa Unggulan Kemendikbud 2025',
                'deskripsi' => 'Beasiswa prestasi dari Kementerian Pendidikan dan Kebudayaan',
                'universitas' => 'PTN Terbaik Indonesia',
                'jenis_beasiswa' => 'Beasiswa Prestasi',
                'jenjang' => 'S1/S2/S3',
                'kategori' => 'Teknik',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonth(),
                'ipk_minimal' => 3.50,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Beasiswa Bank Indonesia 2025',
                'deskripsi' => 'Beasiswa dari Bank Indonesia untuk mahasiswa berprestasi',
                'universitas' => 'Universitas Terpilih',
                'jenis_beasiswa' => 'Beasiswa Parsial',
                'jenjang' => 'S1',
                'kategori' => 'Ekonomi & Bisnis',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(2)->addDays(15),
                'ipk_minimal' => 3.25,
                'jurusan' => 'Ekonomi, Akuntansi, Manajemen',
            ],
            [
                'nama' => 'Beasiswa Djarum Plus 2025',
                'deskripsi' => 'Beasiswa untuk mahasiswa berprestasi dengan program pengembangan soft skills',
                'universitas' => '50 Universitas Terbaik',
                'jenis_beasiswa' => 'Beasiswa Prestasi',
                'jenjang' => 'S1',
                'kategori' => 'Sosial & Humaniora',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addDays(45),
                'ipk_minimal' => 3.00,
                'jurusan' => 'Semua Jurusan',
            ],

            // Beasiswa Luar Negeri
            [
                'nama' => 'MEXT Scholarship Japan 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Jepang untuk studi S2 dan S3',
                'universitas' => 'Universitas di Jepang',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S2/S3',
                'kategori' => 'Teknik',
                'negara' => 'Jepang',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(4),
                'ipk_minimal' => 3.00,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Korean Government Scholarship (KGSP) 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Korea Selatan',
                'universitas' => 'Universitas di Korea Selatan',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S1/S2/S3',
                'kategori' => 'Sains & Teknologi',
                'negara' => 'Korea',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(3)->addDays(10),
                'ipk_minimal' => 2.75,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Chevening Scholarship UK 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Inggris untuk studi S2',
                'universitas' => 'Universitas di Inggris',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S2',
                'kategori' => 'Sosial & Humaniora',
                'negara' => 'Inggris',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(5),
                'ipk_minimal' => 3.25,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Australia Awards Scholarship 2025',
                'deskripsi' => 'Beasiswa penuh dari pemerintah Australia untuk studi S2',
                'universitas' => 'Universitas di Australia',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S2',
                'kategori' => 'Kesehatan',
                'negara' => 'Australia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(6),
                'ipk_minimal' => 2.90,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Fulbright Scholarship USA 2025',
                'deskripsi' => 'Beasiswa bergengsi dari pemerintah Amerika Serikat',
                'universitas' => 'Universitas di Amerika Serikat',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S2/S3',
                'kategori' => 'Sains & Teknologi',
                'negara' => 'Amerika',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(7),
                'ipk_minimal' => 3.50,
                'jurusan' => 'Semua Jurusan',
            ],
            [
                'nama' => 'Orange Tulip Scholarship Netherlands 2025',
                'deskripsi' => 'Beasiswa dari Belanda untuk mahasiswa Indonesia',
                'universitas' => 'Universitas di Belanda',
                'jenis_beasiswa' => 'Beasiswa Parsial',
                'jenjang' => 'S1/S2',
                'kategori' => 'Ekonomi & Bisnis',
                'negara' => 'Belanda',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(4)->addDays(20),
                'ipk_minimal' => 3.00,
                'jurusan' => 'Business, Engineering, IT',
            ],
            [
                'nama' => 'DAAD Scholarship Germany 2025',
                'deskripsi' => 'Beasiswa dari pemerintah Jerman untuk berbagai jenjang',
                'universitas' => 'Universitas di Jerman',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S2/S3',
                'kategori' => 'Teknik',
                'negara' => 'Jerman',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addMonths(5)->addDays(15),
                'ipk_minimal' => 3.25,
                'jurusan' => 'Engineering, Science',
            ],

            // Beasiswa Swasta
            [
                'nama' => 'Beasiswa Tanoto Foundation 2025',
                'deskripsi' => 'Beasiswa untuk mahasiswa berprestasi dari keluarga kurang mampu',
                'universitas' => 'Universitas Mitra',
                'jenis_beasiswa' => 'Beasiswa Penuh',
                'jenjang' => 'S1',
                'kategori' => 'Sosial & Humaniora',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addDays(60),
                'ipk_minimal' => 3.00,
                'jurusan' => 'Pendidikan, Kesehatan',
            ],
            [
                'nama' => 'Beasiswa Orbit Future Academy 2025',
                'deskripsi' => 'Beasiswa untuk bidang teknologi dan digital',
                'universitas' => 'Partner Universities',
                'jenis_beasiswa' => 'Beasiswa Parsial',
                'jenjang' => 'S1',
                'kategori' => 'Sains & Teknologi',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addDays(90),
                'ipk_minimal' => 2.75,
                'jurusan' => 'IT, Computer Science, Data Science',
            ],
            [
                'nama' => 'Beasiswa Superbank 2025',
                'deskripsi' => 'Beasiswa dari perbankan untuk mahasiswa S1 aktif',
                'universitas' => 'PTN/PTS Terpilih',
                'jenis_beasiswa' => 'Beasiswa Parsial',
                'jenjang' => 'S1',
                'kategori' => 'Ekonomi & Bisnis',
                'negara' => 'Indonesia',
                'status' => 'Aktif',
                'deadline' => Carbon::now()->addDays(75),
                'ipk_minimal' => 3.00,
                'jurusan' => 'Ekonomi, Akuntansi, Perbankan',
            ],
        ];

        foreach ($beasiswas as $beasiswa) {
            Beasiswa::create($beasiswa);
        }
    }
}
