<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tryout;
use Carbon\Carbon;

class TryoutSeeder extends Seeder
{
    public function run()
    {
        $tryouts = [
            // UTBK/SNBT - Online
            [
                'nama_tryout' => 'Try Out UTBK-SNBT Nasional 2025 #1',
                'deskripsi' => 'Try out UTBK-SNBT dengan sistem berbasis komputer yang mensimulasikan ujian sebenarnya',
                'penyelenggara' => 'Ruangguru',
                'kategori' => 'UTBK',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(7),
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '12:00:00',
                'lokasi' => 'Online',
                'biaya' => 0,
                'link_pendaftaran' => 'https://ruangguru.com/tryout',
                'deadline_pendaftaran' => Carbon::now()->addDays(5),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
            [
                'nama_tryout' => 'SNBT Preparation Test - Zenius',
                'deskripsi' => 'Persiapan SNBT dengan soal-soal prediksi akurat dan pembahasan lengkap',
                'penyelenggara' => 'Zenius',
                'kategori' => 'SNBT',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(10),
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '11:30:00',
                'lokasi' => 'Online',
                'biaya' => 25000,
                'link_pendaftaran' => 'https://zenius.net/tryout',
                'deadline_pendaftaran' => Carbon::now()->addDays(8),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => false,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
            [
                'nama_tryout' => 'Mega Try Out UTBK 2025',
                'deskripsi' => 'Try out massal dengan peserta dari seluruh Indonesia',
                'penyelenggara' => 'Quipper',
                'kategori' => 'UTBK',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(14),
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '16:30:00',
                'lokasi' => 'Online',
                'biaya' => 0,
                'link_pendaftaran' => 'https://quipper.com/tryout',
                'deadline_pendaftaran' => Carbon::now()->addDays(12),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => true,
                'is_active' => true,
            ],

            // Ujian Mandiri - Offline
            [
                'nama_tryout' => 'Simulasi UM UGM 2025',
                'deskripsi' => 'Try out khusus untuk persiapan Ujian Mandiri UGM dengan pola soal terbaru',
                'penyelenggara' => 'Bimbel Ganesha Operation',
                'kategori' => 'Ujian Mandiri',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(20),
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '12:00:00',
                'lokasi' => 'Yogyakarta',
                'biaya' => 50000,
                'link_pendaftaran' => 'https://go-ugm.com',
                'deadline_pendaftaran' => Carbon::now()->addDays(17),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
            [
                'nama_tryout' => 'Try Out UM ITB Premium',
                'deskripsi' => 'Persiapan intensif Ujian Mandiri ITB dengan instruktur berpengalaman',
                'penyelenggara' => 'Bimbel Neutron',
                'kategori' => 'Ujian Mandiri',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(25),
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '13:00:00',
                'lokasi' => 'Bandung',
                'biaya' => 75000,
                'link_pendaftaran' => 'https://neutron.ac.id',
                'deadline_pendaftaran' => Carbon::now()->addDays(22),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => false,
                'is_active' => true,
            ],

            // Kedinasan
            [
                'nama_tryout' => 'Simulasi SPMB PKN STAN 2025',
                'deskripsi' => 'Try out lengkap untuk persiapan masuk PKN STAN',
                'penyelenggara' => 'Bimbel STAN Indonesia',
                'kategori' => 'Kedinasan',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(15),
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '10:30:00',
                'lokasi' => 'Jakarta',
                'biaya' => 30000,
                'link_pendaftaran' => 'https://stan-indonesia.com',
                'deadline_pendaftaran' => Carbon::now()->addDays(13),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => false,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
            [
                'nama_tryout' => 'Try Out IPDN 2025',
                'deskripsi' => 'Persiapan seleksi masuk Institut Pemerintahan Dalam Negeri',
                'penyelenggara' => 'Pahamify',
                'kategori' => 'Kedinasan',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(18),
                'waktu_mulai' => '14:00:00',
                'waktu_selesai' => '17:00:00',
                'lokasi' => 'Online',
                'biaya' => 0,
                'link_pendaftaran' => 'https://pahamify.com/ipdn',
                'deadline_pendaftaran' => Carbon::now()->addDays(16),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => true,
                'is_active' => true,
            ],

            // Mix Online/Offline
            [
                'nama_tryout' => 'Try Out Komprehensif UTBK-SNBT',
                'deskripsi' => 'Try out dengan analisis mendalam dan prediksi passing grade PTN favorit',
                'penyelenggara' => 'Bimbel Nurul Fikri',
                'kategori' => 'SNBT',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(30),
                'waktu_mulai' => '07:30:00',
                'waktu_selesai' => '11:30:00',
                'lokasi' => 'Jakarta',
                'biaya' => 100000,
                'link_pendaftaran' => 'https://nurulfikri.ac.id',
                'deadline_pendaftaran' => Carbon::now()->addDays(27),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
            [
                'nama_tryout' => 'UTBK Challenge - Eduka System',
                'deskripsi' => 'Try out dengan sistem adaptive testing sesuai kemampuan peserta',
                'penyelenggara' => 'Eduka System',
                'kategori' => 'UTBK',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(21),
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '13:30:00',
                'lokasi' => 'Surabaya',
                'biaya' => 45000,
                'link_pendaftaran' => 'https://edukasystem.com',
                'deadline_pendaftaran' => Carbon::now()->addDays(19),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => false,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
            [
                'nama_tryout' => 'Simulasi UM UNPAD 2025',
                'deskripsi' => 'Try out khusus persiapan Ujian Mandiri Universitas Padjadjaran',
                'penyelenggara' => 'SSC Intersolusi',
                'kategori' => 'Ujian Mandiri',
                'tanggal_pelaksanaan' => Carbon::now()->addDays(28),
                'waktu_mulai' => '08:30:00',
                'waktu_selesai' => '12:30:00',
                'lokasi' => 'Bandung',
                'biaya' => 60000,
                'link_pendaftaran' => 'https://sscintersolusi.com',
                'deadline_pendaftaran' => Carbon::now()->addDays(25),
                'dengan_pembahasan' => true,
                'dengan_sertifikat' => true,
                'dengan_ranking' => true,
                'is_active' => true,
            ],
        ];

        foreach ($tryouts as $tryout) {
            Tryout::create($tryout);
        }
    }
}
